const $=s=>document.querySelector(s);
const money=new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0});
const app={step:2,start:null,context:{},dataset:null,datasetName:'',source:'',analysis:null,uploadNames:{sales:'',inventory:''},rawUploads:{sales:null,inventory:null},interpretations:{sales:null,inventory:null},semanticPending:false,tasks:['Pendiente','Pendiente','Pendiente'],owners:['Gerencia','',''],activePriority:0,feedback:{},completed:{start:false,form:false,data:false,quality:false,priority:false,plan:false,feedback:false}};
const stepNames=['Bienvenida','Conozcamos tu negocio','Carga de información','Calidad de tus datos','Tus tres prioridades','Atiende esto primero','Plan de acción','Seguimiento','Retroalimentación','Siguiente prioridad'];
const stageByStep={1:1,2:1,3:2,4:2,5:3,6:3,7:4,8:4,9:4,10:4};
const stageNames=['Conoce tu negocio','Analiza tus datos','Descubre tus prioridades','Actúa y haz seguimiento'];

const datasets={
  detenido:{name:'Caso 1 · Inventario detenido',sales:[
    ['2026-04-05','Cafetera clásica',2,185000],['2026-04-18','Licuadora práctica',7,142000],['2026-05-02','Cafetera clásica',1,185000],['2026-05-12','Juego de ollas',12,265000],['2026-05-26','Licuadora práctica',8,142000],['2026-06-04','Vajilla blanca',1,198000],['2026-06-15','Juego de ollas',15,265000],['2026-06-28','Licuadora práctica',9,142000],['2026-07-03','Cafetera clásica',1,185000],['2026-07-11','Juego de ollas',13,265000],['2026-07-19','Licuadora práctica',8,142000],['2026-07-25','Vajilla blanca',1,198000]
  ].map(x=>({fecha:x[0],producto:x[1],cantidad:x[2],precio:x[3]})),inventory:[['Cafetera clásica',64,128000],['Licuadora práctica',18,97000],['Juego de ollas',16,181000],['Vajilla blanca',48,136000],['Sartén antiadherente',7,68000]].map(x=>({producto:x[0],stock:x[1],costo:x[2]}))},
  concentrado:{name:'Caso 2 · Ventas concentradas',sales:[
    ['2026-04-03','Arroz premium 5 kg',42,24500],['2026-04-16','Arroz premium 5 kg',48,24500],['2026-05-01','Arroz premium 5 kg',55,24500],['2026-05-18','Aceite vegetal 1 L',8,11900],['2026-05-27','Arroz premium 5 kg',51,24500],['2026-06-02','Arroz premium 5 kg',60,24500],['2026-06-14','Café molido 500 g',4,18900],['2026-06-29','Arroz premium 5 kg',57,24500],['2026-07-05','Arroz premium 5 kg',62,24500],['2026-07-14','Azúcar 1 kg',5,4800],['2026-07-21','Arroz premium 5 kg',58,24500],['2026-07-27','Aceite vegetal 1 L',6,11900]
  ].map(x=>({fecha:x[0],producto:x[1],cantidad:x[2],precio:x[3]})),inventory:[['Arroz premium 5 kg',70,18700],['Aceite vegetal 1 L',4,8200],['Café molido 500 g',22,13400],['Azúcar 1 kg',35,3500]].map(x=>({producto:x[0],stock:x[1],costo:x[2]}))},
  insuficiente:{name:'Caso 3 · Información insuficiente',sales:[{fecha:'fecha desconocida',producto:'Cuaderno grande',cantidad:'',precio:8500},{fecha:'2026-07-10',producto:'',cantidad:-3,precio:'sin dato'}],inventory:[{producto:'Cuaderno grande',stock:'',costo:4200}]}
};

const aliases={producto:['producto','articulo','referencia','sku','item'],fecha:['fecha','fecha venta','fecha de venta'],cantidad:['cantidad','unidades','cant','qty'],precio:['precio','precio venta','valor unitario','precio unitario'],stock:['existencia','stock','inventario','cantidad disponible'],costo:['costo','costo unitario','valor costo']};
const semanticRoles={
  sales:{
    fecha:{label:'Fecha de venta',required:true,terms:['fecha','dia','periodo','fecha factura','fecha operacion']},
    producto:{label:'Producto',required:true,terms:['producto','articulo','descripcion','referencia','sku','item','codigo','mercancia']},
    cantidad:{label:'Cantidad vendida',required:true,terms:['cantidad','unidades','cant','qty','movimientos','despacho','volumen','unid vendidas']},
    precio:{label:'Precio unitario',required:false,terms:['precio','precio venta','valor unitario','precio unitario','vr unitario']},
    valorTotal:{label:'Valor total de venta',required:false,terms:['valor total','total venta','vr neto','valor neto','importe','subtotal','ingreso','total factura']},
    costo:{label:'Costo',required:false,terms:['costo','coste','valor costo']},
    cliente:{label:'Cliente',required:false,terms:['cliente','comprador','tercero']},
    canal:{label:'Canal',required:false,terms:['canal','medio venta','sucursal','tienda']}
  },
  inventory:{
    producto:{label:'Producto',required:true,terms:['producto','articulo','descripcion','referencia','sku','item','codigo','mercancia']},
    stock:{label:'Existencia actual',required:true,terms:['existencia','stock','inventario','saldo','disponible','cantidad disponible','existencia actual']},
    costo:{label:'Costo',required:false,terms:['costo','coste','valor costo']},
    ultimoMovimiento:{label:'Último movimiento',required:false,terms:['ultimo movimiento','fecha movimiento','ultima salida','ultima entrada']},
    referencia:{label:'Referencia o código',required:false,terms:['referencia','codigo','sku interno','sku']}
  }
};
const roleLabels=Object.fromEntries(Object.values(semanticRoles).flatMap(group=>Object.entries(group).map(([key,value])=>[key,value.label])));
const normalize=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[._-]/g,' ').replace(/\s+/g,' ').trim();
const safe=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

function startDemo(){$('#welcome-view').classList.add('hidden');$('#app-view').classList.remove('hidden');app.start=Date.now();app.completed.start=true;go(2);}
$('#start-demo').addEventListener('click',startDemo);
$('#restart-button').addEventListener('click',()=>{location.reload()});
$('#test-summary-button').addEventListener('click',showTestSummary);
$('.dialog-close').addEventListener('click',()=>$('#test-dialog').close());

function go(step){app.step=Math.max(1,Math.min(10,step));render();window.scrollTo({top:0,behavior:'smooth'});}
function render(){const stage=stageByStep[app.step];$('#progress-label').textContent=`Etapa ${stage} de 4 · ${stageNames[stage-1]}`;$('#progress-title').textContent=stepNames[app.step-1];$('#progress-bar').style.width=`${stage/4*100}%`;const screens=[welcome,contextScreen,dataScreen,qualityScreen,prioritiesScreen,focusScreen,planScreen,followupScreen,feedbackScreen,nextScreen];$('#screen').innerHTML=screens[app.step-1]();$('#screen').focus({preventScroll:true});bindScreen();}
function nav(back,next,label='Continuar'){return `<div class="actions">${back?`<button class="button secondary" type="button" data-go="${back}">← Volver</button>`:'<span></span>'}<div class="right">${next?`<button class="button gold" type="button" data-go="${next}">${label} →</button>`:''}</div></div>`;}

function welcome(){return `<section class="hero-screen"><div><p class="eyebrow">Bienvenido a la demostración</p><h1>Tus datos te muestran qué atender primero.</h1><p>San José revisará información ficticia de ventas e inventario, explicará qué tan útil es y propondrá un paso concreto. Tú conservas siempre la decisión final.</p><button class="button gold" type="button" data-go="2">Comenzar recorrido →</button></div><aside class="hero-visual"><p class="eyebrow">Lo haremos en pocos pasos</p><h3>De información dispersa a una acción clara</h3><div class="flow-list"><div><span>1</span>Conocer el negocio</div><div><span>2</span>Revisar la información</div><div><span>3</span>Elegir una prioridad</div><div><span>4</span>Actuar y hacer seguimiento</div></div></aside></section>`;}

function contextScreen(){return `<p class="eyebrow">Conozcamos tu negocio</p><h1 class="screen-title">Cuéntanos lo esencial</h1><p class="screen-intro">Estas respuestas ayudan a poner la orientación en contexto. Para la demostración, no escribas información personal real.</p><form id="context-form" class="panel"><div class="form-grid">
<label>¿A qué se dedica tu negocio? *<select name="actividad" required><option value="">Selecciona</option><option>Comercio minorista</option><option>Comercio mayorista</option><option>Distribución</option></select></label>
<label>¿Cuánto tiempo lleva funcionando? *<select name="antiguedad" required><option value="">Selecciona</option><option>Menos de 2 años</option><option>2 a 5 años</option><option>6 a 10 años</option><option>Más de 10 años</option></select></label>
<label>¿Cómo registras tus ventas? *<select name="registro" required><option value="">Selecciona</option><option>Excel o Google Sheets</option><option>Sistema POS</option><option>Software contable</option><option>Cuaderno o registros manuales</option></select></label>
<label>¿Qué te preocupa más hoy? *<select name="preocupacion" required><option value="">Selecciona</option><option>Productos que no se venden</option><option>Quedarme sin productos</option><option>Depender de pocas ventas</option><option>No confiar en mis datos</option></select></label>
<label>¿Qué quieres mejorar primero? *<select name="objetivo" required><option value="">Selecciona</option><option>Rotación del inventario</option><option>Disponibilidad de productos</option><option>Ventas</option><option>Calidad de la información</option></select></label>
<label>¿Has recibido apoyo de consultoría o herramientas de análisis? *<select name="apoyo" required><option value="">Selecciona</option><option>Sí</option><option>No</option></select></label>
<label>¿Has intentado solucionar antes este problema? *<select id="attempt-select" name="intento" required><option value="">Selecciona</option><option>Sí, pero no funcionó como esperaba</option><option>Sí, y tuve resultados parciales</option><option>No</option></select></label>
</div><div id="blocker-question" class="conditional hidden"><label>¿Qué crees que impidió que funcionara?<textarea name="obstaculo" rows="3" placeholder="Respuesta corta"></textarea></label></div><div class="actions"><button class="button secondary" id="back-to-welcome" type="button">← Volver</button><button class="button gold" type="submit">Guardar y continuar →</button></div></form>`;}

function dataScreen(){return `<p class="eyebrow">Carga de información</p><h1 class="screen-title">Elige cómo probar San José</h1><p class="screen-intro">Analizamos inicialmente tus ventas e inventario para ayudarte a identificar qué atender primero. La forma más rápida es usar uno de los tres casos ficticios; también puedes cargar tus archivos como los utilizas normalmente.</p><div class="truth-strip">El procesamiento ocurre localmente en este navegador. San José no envía ni almacena tus archivos en un servidor.</div><div class="recommend-box"><article><h3>Para ventas</h3><p>Conviene tener fecha, producto, unidades y algún valor de venta. <a href="datos/plantilla_ventas.csv" download>Descargar plantilla</a></p></article><article><h3>Para inventario</h3><p>Conviene tener producto y existencia actual. <a href="datos/plantilla_inventario.csv" download>Descargar plantilla</a></p></article></div><div class="choice-grid">
${Object.entries(datasets).map(([k,d])=>`<button class="choice-card ${app.source===k?'selected':''}" type="button" data-dataset="${k}"><span class="case-tag">Datos completamente ficticios</span><strong>${d.name}</strong><span>${k==='detenido'?'Productos almacenados con pocas ventas.':k==='concentrado'?'Un producto representa gran parte de los ingresos.':'Datos faltantes e inconsistentes; no debe recomendar.'}</span></button>`).join('')}</div>
<section class="panel"><h2>O carga tus archivos anonimizados</h2><p><strong>Puedes cargar archivos Excel (.xlsx, .xls) o CSV.</strong></p><p class="screen-intro">Carga tus archivos como los utilizas normalmente. San José revisará la información e intentará identificar automáticamente los datos necesarios para el análisis.</p><p class="screen-intro">Si no logramos identificar algún dato importante, te diremos exactamente qué información necesitamos.</p><div class="form-grid"><label class="upload-box">Ventas<input id="sales-file" type="file" accept=".xlsx,.xls,.csv,text/csv,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"><span id="sales-file-status" class="file-status ${app.uploadNames.sales?'success':''}">${app.uploadNames.sales?`✓ ${safe(app.uploadNames.sales)}`:'Sin archivo'}</span></label><label class="upload-box">Inventario<input id="inventory-file" type="file" accept=".xlsx,.xls,.csv,text/csv,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"><span id="inventory-file-status" class="file-status ${app.uploadNames.inventory?'success':''}">${app.uploadNames.inventory?`✓ ${safe(app.uploadNames.inventory)}`:'Sin archivo'}</span></label></div><p id="upload-error" class="message error" role="alert"></p></section>${app.semanticPending?interpretationPanel():nav(2,app.dataset?4:null,'Procesar información')}`;}

function interpretationPanel(){const issues=requiredMappingIssues();const preliminary=issues.length?'BAJA':Object.values(app.interpretations).some(group=>Object.values(group.assignments).some(a=>a&&a.confidence==='Media'))?'MEDIA':'ALTA';const optional=[],usable=a=>a&&a.confidence!=='Baja';if(!usable(app.interpretations.sales.assignments.costo)&&!usable(app.interpretations.inventory.assignments.costo))optional.push('No encontramos información de costos. Podemos analizar ventas e inventario, pero no podremos evaluar margen o rentabilidad.');return `<section class="panel interpretation-panel"><p class="eyebrow">Interpretación automatizada</p><h2>Así entendimos tus datos</h2><p>Esta confirmación es una parte central del análisis. Revisa qué columna encontramos, cómo la interpretamos y una muestra de sus valores antes de continuar.</p><div class="truth-strip">San José no inventa respuestas. Si una correspondencia esencial no es suficientemente confiable, el análisis se detiene hasta que la confirmes.</div><div class="preliminary"><strong>Calidad preliminar: ${preliminary}</strong><span>${preliminary==='ALTA'?'Encontramos con buena confianza la información esencial.':preliminary==='MEDIA'?'Hay correspondencias que conviene revisar.':'Falta identificar información indispensable.'}</span></div><div class="mapping-grid"><section><h3>Archivo de ventas</h3>${mappingRows('sales')}</section><section><h3>Archivo de inventario</h3>${mappingRows('inventory')}</section></div>${optional.map(x=>`<p class="optional-note">${safe(x)}</p>`).join('')}<div id="mapping-issues">${issues.map(x=>`<div class="low-stop"><p>${safe(x.message)}</p><small>${safe(x.help)}</small></div>`).join('')}</div><div class="actions"><button class="button secondary" type="button" data-go="2">← Volver</button><button id="confirm-mapping" class="button gold" type="button" ${issues.length?'disabled':''}>Confirmar y analizar →</button></div></section>`;}
function mappingRows(type){const interpretation=app.interpretations[type],roles=semanticRoles[type];return Object.entries(roles).map(([role,config])=>{const a=interpretation.assignments[role];const options=interpretation.headers.map(h=>`<option value="${safe(h)}" ${a?.header===h?'selected':''}>${safe(h)}</option>`).join('');return `<div class="mapping-row"><div class="mapping-found"><span>Columna encontrada</span><strong>${a?safe(a.header):'No identificada'}</strong><small>${a?.sample?`Ejemplo: ${safe(a.sample)}`:'Sin muestra disponible'}</small></div><div class="mapping-proposal"><span>Interpretación propuesta</span><strong>→ ${config.label}</strong><small class="confidence ${a?.confidence?.toLowerCase()||'none'}">Confianza: ${a?.confidence||'Sin definir'}</small></div><label>Corrección manual<select class="mapping-select" data-file="${type}" data-role="${role}"><option value="">No está en el archivo</option>${options}</select></label></div>`}).join('');}
function requiredMappingIssues(){const issues=[];const sales=app.interpretations.sales?.assignments||{},inv=app.interpretations.inventory?.assignments||{};const usable=a=>a&&a.header&&a.confidence!=='Baja';if(!usable(sales.fecha))issues.push({message:'Revisamos tu archivo, pero no encontramos una fecha de venta con suficiente confianza.',help:'Busca una columna que indique cuándo ocurrió cada venta y selecciónala arriba.'});if(!usable(sales.producto))issues.push({message:'No logramos identificar con suficiente confianza el producto vendido.',help:'Busca una descripción, referencia, código, SKU o nombre de artículo y selecciónalo arriba.'});if(!usable(sales.cantidad))issues.push({message:'Revisamos tu archivo, pero no encontramos información que podamos identificar con suficiente confianza como cantidad vendida.',help:'Busca en tu archivo una columna que indique cuántas unidades se vendieron por producto o transacción y vuelve a cargarlo o selecciónala arriba.'});if(!usable(sales.precio)&&!usable(sales.valorTotal))issues.push({message:'No logramos identificar un precio unitario ni un valor total de venta.',help:'Busca una columna con el precio por unidad o el total de cada venta y selecciónala arriba.'});if(!usable(inv.producto))issues.push({message:'No logramos identificar el producto en el archivo de inventario.',help:'Busca una descripción, referencia, código o SKU y selecciónalo arriba.'});if(!usable(inv.stock))issues.push({message:'No logramos identificar la existencia actual del inventario.',help:'Busca una columna que indique cuántas unidades hay disponibles y selecciónala arriba.'});return issues;}

function qualityScreen(){if(!app.analysis)return missingState();const q=app.analysis.quality;return `<p class="eyebrow">Control de calidad</p><h1 class="screen-title">¿Podemos orientar una decisión con estos datos?</h1><div class="quality-layout"><article class="quality-card"><span class="level ${q.level.toLowerCase()}">Calidad ${q.level}</span><h2>${q.score}/100</h2><p>${q.explanation}</p><small>Fuente: ${safe(app.datasetName)}</small></article><section class="panel"><h2>Lo que verificamos antes de recomendar</h2><ul class="check-list">${q.checks.map(x=>`<li class="${x.ok?'':'problem'}">${safe(x.text)}</li>`).join('')}</ul></section></div>${q.level==='BAJA'?`<div class="low-stop"><h3>Todavía no tenemos suficiente información para recomendar con confianza.</h3><p>Revisa los puntos marcados arriba y completa o corrige esos datos. Detenerse aquí es el comportamiento correcto: San José no inventa cifras ni fuerza una recomendación cuando falta evidencia.</p></div>${nav(3,null)}`:nav(3,5,'Descubrir prioridades')}`;}

function priorityGuidance(p){const guidance={slow:{meaning:'El dinero y el espacio de bodega permanecen comprometidos en productos con poca salida.',action:'Confirmar las existencias y definir si conviene promover, combinar, liquidar o pausar temporalmente nuevas compras.'},concentration:{meaning:'Una caída en el producto principal puede afectar una parte importante de los ingresos observados.',action:'Validar si el patrón se mantiene y probar dos productos complementarios que ayuden a distribuir mejor las ventas.'},stockout:{meaning:'Una existencia muy baja puede convertirse en ventas perdidas si el producto continúa moviéndose.',action:'Verificar físicamente la existencia y ajustar el siguiente pedido con base en ventas recientes y tiempos del proveedor.'},review:{meaning:'Los productos con menor movimiento pueden requerir una decisión comercial o una revisión del registro.',action:'Confirmar los datos y revisar una mejora pequeña en exhibición, promoción o compra.'},maintain:{meaning:'Proteger la disponibilidad de los productos principales ayuda a sostener las ventas registradas.',action:'Vigilar las existencias y anticipar la reposición sin comprar a ciegas.'},data:{meaning:'Una actualización constante permite distinguir un patrón real de una observación aislada.',action:'Definir un día semanal para actualizar ventas e inventario sin interrupciones.'}};return guidance[p.type]||guidance.review;}

function prioritiesScreen(){if(!app.analysis||app.analysis.quality.level==='BAJA')return missingState();app.completed.priority=true;const [main,...others]=app.analysis.priorities,guide=priorityGuidance(main);return `<p class="eyebrow">Decisión primero</p><div class="priority-heading"><div><h1 class="screen-title">Tu principal prioridad</h1><p class="screen-intro">La orientación se basa únicamente en tus ventas e inventario y en la evidencia disponible.</p></div><button id="download-summary" class="button secondary" type="button">Descargar resumen ejecutivo</button></div><article class="main-priority"><span class="rank">PRIORIDAD 1 · ATIENDE ESTO PRIMERO</span><h2>${safe(main.title)}</h2><div class="consulting-grid"><section><span>Qué detectamos</span><p>${safe(main.reason)}</p></section><section><span>Qué significa para el negocio</span><p>${safe(guide.meaning)}</p></section><section><span>Qué evidencia lo demuestra</span><p><strong>${safe(main.evidence)}</strong></p></section><section><span>Qué hacer primero</span><p>${safe(guide.action)}</p></section></div><div class="priority-actions"><button class="button secondary light" type="button" data-priority="0" data-go="6">Ver evidencia</button><button class="button gold" type="button" data-plan="0">Crear plan de acción</button></div></article><section class="secondary-priorities"><h2>Después de la prioridad principal</h2><div class="priority-grid">${others.map((p,i)=>{const g=priorityGuidance(p);return `<article class="priority"><span class="rank">PRIORIDAD ${i+2}</span><h3>${safe(p.title)}</h3><p>${safe(g.meaning)}</p><button class="text-link" type="button" data-priority="${i+1}" data-go="6">Revisar evidencia →</button></article>`}).join('')}</div></section><details class="evidence-details"><summary>Ver indicadores que sustentan el análisis</summary><div class="stats-grid">${metricCards()}</div></details>${nav(4,null)}`;}

function focusScreen(){const index=app.activePriority||0,p=app.analysis?.priorities[index];if(!p)return missingState();const guide=priorityGuidance(p);return `<p class="eyebrow">Evidencia de la prioridad ${index+1}</p><h1 class="screen-title">${safe(p.title)}</h1><article class="focus-card"><div><span>Qué detectamos</span><h2>${safe(p.reason)}</h2></div><div class="why"><strong>Evidencia calculada</strong><p>${safe(p.evidence)}</p></div></article><div class="consulting-detail"><section class="panel"><h2>Qué significa para el negocio</h2><p>${safe(guide.meaning)}</p></section><section class="panel"><h2>Qué conviene hacer primero</h2><p>${safe(guide.action)}</p><p><strong>Indicador de seguimiento:</strong> ${safe(p.indicator)}</p></section></div><div class="actions"><button class="button secondary" type="button" data-go="5">← Volver a prioridades</button>${index===0?'<button class="button gold" type="button" data-plan="0">Crear plan de acción →</button>':''}</div>`;}

function planScreen(){if(!app.analysis)return missingState();app.completed.plan=true;const plan=getPlan(),indicator=app.analysis.priorities[0].indicator;return `<p class="eyebrow">De la prioridad a la ejecución</p><h1 class="screen-title">Plan de acción</h1><p class="screen-intro">Cada actividad responde directamente a <strong>${safe(app.analysis.priorities[0].title)}</strong>. Define quién la liderará y revisa el indicador acordado.</p><div class="timeline">${plan.map((x,i)=>`<article class="task-card"><span class="when">${x.when}</span><h3>${safe(x.action)}</h3><p>${safe(x.explain)}</p><label>Responsable<input class="task-owner" data-task="${i}" value="${safe(app.owners[i])}" placeholder="Nombre o cargo"></label><div class="task-indicator"><span>Indicador</span><p>${safe(indicator)}</p></div><label>Estado<select class="task-state" data-task="${i}"><option ${app.tasks[i]==='Pendiente'?'selected':''}>Pendiente</option><option ${app.tasks[i]==='En proceso'?'selected':''}>En proceso</option><option ${app.tasks[i]==='Completada'?'selected':''}>Completada</option></select></label></article>`).join('')}</div>${nav(6,8,'Hacer seguimiento')}`;}

function followupScreen(){const done=app.tasks.filter(x=>x==='Completada').length,indicator=app.analysis?.priorities[0]?.indicator||'';return `<p class="eyebrow">Seguimiento de la decisión</p><h1 class="screen-title">Convierte la prioridad en avance</h1><div class="progress-counter"><strong id="task-count">${done}/3</strong><span>acciones completadas</span></div><div class="followup-summary"><span>Indicador acordado</span><strong>${safe(indicator)}</strong></div><div class="timeline compact">${getPlan().map((x,i)=>`<article class="task-card"><span class="when">${x.when}</span><h3>${safe(x.action)}</h3><p><strong>Responsable:</strong> ${safe(app.owners[i]||'Por definir')}</p><label>Estado<select class="task-state" data-task="${i}"><option ${app.tasks[i]==='Pendiente'?'selected':''}>Pendiente</option><option ${app.tasks[i]==='En proceso'?'selected':''}>En proceso</option><option ${app.tasks[i]==='Completada'?'selected':''}>Completada</option></select></label></article>`).join('')}</div>${nav(7,9,'Registrar avance')}`;}

function feedbackScreen(){return `<p class="eyebrow">Retroalimentación</p><h1 class="screen-title">Cuéntanos qué pasó</h1><p class="screen-intro">Para la demostración puedes responder incluso si las acciones no están completas.</p><form id="feedback-form" class="panel"><div class="feedback-grid"><fieldset><legend>¿Pudiste completar el plan? *</legend><div class="radio-group">${radio('complete',['Sí','Parcialmente','No'])}</div></fieldset><fieldset><legend>¿Notaste alguna mejora? *</legend><div class="radio-group">${radio('improved',['Sí','Todavía no','No estoy seguro'])}</div></fieldset></div><label>Cuéntanos brevemente qué pasó (opcional)<textarea name="comment" rows="4"></textarea></label><div class="actions"><button class="button secondary" type="button" data-go="8">← Volver</button><button class="button gold" type="submit">Guardar y continuar →</button></div></form>`;}

function nextScreen(){const main=app.analysis?.priorities[0],next=app.analysis?.priorities[1],plan=getPlan();return `<p class="eyebrow">Continuidad</p><h1 class="screen-title">Ya tienes una primera prioridad. Ahora conviértela en resultado.</h1><div class="continuity-grid"><article class="completion"><span>Principal hallazgo</span><h2>${safe(main?.title||'Completar la información pendiente')}</h2><p>${safe(main?.evidence||'Aún no hay evidencia suficiente.')}</p></article><article class="panel"><span>Acción acordada</span><h3>${safe(plan[0]?.action||'Revisar la información pendiente')}</h3><p><strong>Indicador:</strong> ${safe(main?.indicator||'Por definir')}</p></article><article class="panel"><span>Siguiente prioridad pendiente</span><h3>${safe(next?.title||'Mantener actualizado el análisis')}</h3><p>${safe(next?.reason||'Amplía la información antes de continuar.')}</p></article></div><div class="final-actions"><button class="button secondary" type="button" data-go="7">Revisar plan</button><button class="button secondary" type="button" data-priority="1" data-go="6">Analizar siguiente prioridad</button><button id="download-summary" class="button gold" type="button">Descargar resumen ejecutivo</button><button class="text-button" type="button" id="restart-demo">Reiniciar demostración</button></div>`;}

function radio(name,items){return items.map(x=>`<label class="radio-pill"><input type="radio" name="${name}" value="${x}" required><span>${x}</span></label>`).join('');}
function missingState(){return `<div class="panel"><h2>Primero necesitamos procesar información</h2><p>Regresa al paso de carga y elige un caso ficticio.</p>${nav(null,3,'Volver a los datos')}</div>`;}

function bindScreen(){document.querySelectorAll('[data-priority]').forEach(b=>b.addEventListener('click',()=>{app.activePriority=Number(b.dataset.priority);go(Number(b.dataset.go))}));document.querySelectorAll('[data-go]:not([data-priority])').forEach(b=>b.addEventListener('click',()=>go(Number(b.dataset.go))));document.querySelectorAll('[data-plan]').forEach(b=>b.addEventListener('click',()=>{app.activePriority=0;go(7)}));$('#download-summary')?.addEventListener('click',downloadExecutiveSummary);$('#restart-demo')?.addEventListener('click',()=>location.reload());$('#back-to-welcome')?.addEventListener('click',()=>location.reload());if(app.step===2){$('#context-form').addEventListener('submit',saveContext);$('#attempt-select').addEventListener('change',toggleBlocker);toggleBlocker();}if(app.step===3){document.querySelectorAll('[data-dataset]').forEach(b=>b.addEventListener('click',()=>selectDataset(b.dataset.dataset)));$('#sales-file').addEventListener('change',e=>readUpload(e.target.files[0],'sales'));$('#inventory-file').addEventListener('change',e=>readUpload(e.target.files[0],'inventory'));document.querySelectorAll('.mapping-select').forEach(s=>s.addEventListener('change',changeMapping));$('#confirm-mapping')?.addEventListener('click',confirmInterpretation);}if(app.step===4&&app.analysis)app.completed.quality=true;if(app.step===7||app.step===8){document.querySelectorAll('.task-state').forEach(s=>s.addEventListener('change',updateTask));document.querySelectorAll('.task-owner').forEach(input=>input.addEventListener('input',updateOwner));}if(app.step===9)$('#feedback-form').addEventListener('submit',saveFeedback);}
function toggleBlocker(){const show=$('#attempt-select')?.value==='Sí, pero no funcionó como esperaba';$('#blocker-question')?.classList.toggle('hidden',!show);}
function saveContext(e){e.preventDefault();app.context=Object.fromEntries(new FormData(e.currentTarget));app.completed.form=true;go(3);}
function selectDataset(key){app.source=key;app.dataset=structuredClone(datasets[key]);app.datasetName=datasets[key].name;app.rawUploads={sales:null,inventory:null};app.interpretations={sales:null,inventory:null};app.semanticPending=false;app.uploadNames={sales:'',inventory:''};app.analysis=analyze(app.dataset);app.completed.data=true;render();}
function changeMapping(e){const type=e.target.dataset.file,role=e.target.dataset.role,header=e.target.value;app.interpretations[type].assignments[role]=header?{header,confidence:'Alta',score:99,reason:'correspondencia confirmada manualmente'}:null;render();}
function confirmInterpretation(){if(requiredMappingIssues().length)return;const salesMap=app.interpretations.sales.assignments,invMap=app.interpretations.inventory.assignments,usable=a=>a&&a.confidence!=='Baja';app.dataset={sales:app.rawUploads.sales.rows.map(r=>({fecha:normalizeDateValue(r[salesMap.fecha.header]),producto:r[salesMap.producto.header],cantidad:r[salesMap.cantidad.header],precio:usable(salesMap.precio)?r[salesMap.precio.header]:'',valorTotal:usable(salesMap.valorTotal)?r[salesMap.valorTotal.header]:'',costo:usable(salesMap.costo)?r[salesMap.costo.header]:'',cliente:usable(salesMap.cliente)?r[salesMap.cliente.header]:'',canal:usable(salesMap.canal)?r[salesMap.canal.header]:''})),inventory:app.rawUploads.inventory.rows.map(r=>({producto:r[invMap.producto.header],stock:r[invMap.stock.header],costo:usable(invMap.costo)?r[invMap.costo.header]:0,ultimoMovimiento:usable(invMap.ultimoMovimiento)?r[invMap.ultimoMovimiento.header]:'',referencia:usable(invMap.referencia)?r[invMap.referencia.header]:''}))};app.datasetName='Archivos interpretados y confirmados';app.analysis=analyze(app.dataset);app.semanticPending=false;app.completed.data=true;go(4);}
function normalizeDateValue(value){const s=String(value??'').trim();if(/^\d{4}-\d{2}-\d{2}/.test(s))return s.slice(0,10);const local=s.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/);if(local)return `${local[3]}-${String(local[2]).padStart(2,'0')}-${String(local[1]).padStart(2,'0')}`;const d=new Date(s);return Number.isNaN(d.getTime())?s:d.toISOString().slice(0,10);}

function parseCSV(text){const lines=text.replace(/^\uFEFF/,'').trim().split(/\r?\n/).filter(Boolean);if(lines.length<2)throw new Error('El archivo debe tener encabezados y al menos una fila.');const d=lines[0].includes(';')?';':',';const split=line=>{let out=[],cur='',quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(quoted&&line[i+1]==='"'){cur+='"';i++;}else quoted=!quoted;}else if(c===d&&!quoted){out.push(cur.trim());cur='';}else cur+=c;}out.push(cur.trim());return out};const headers=split(lines[0]);return {headers,rows:lines.slice(1).map(line=>{const vals=split(line);return Object.fromEntries(headers.map((h,i)=>[h,vals[i]??'']))})};}
function findColumn(headers,key){const normal=headers.map(normalize);return headers[normal.findIndex(h=>aliases[key].includes(h))]||null;}
function convert(parsed,type){const needs=type==='sales'?['producto','fecha','cantidad','precio']:['producto','stock'];const found=Object.fromEntries(needs.map(k=>[k,findColumn(parsed.headers,k)]));const missing=needs.filter(k=>!found[k]);if(missing.length){const human={producto:'producto (Producto, Artículo, Referencia, SKU o Item)',fecha:'fecha (Fecha o Fecha de venta)',cantidad:'cantidad (Cantidad, Unidades, Cant. o Qty)',precio:'precio (Precio, Precio venta o Valor unitario)',stock:'existencia (Existencia, Stock, Inventario o Cantidad disponible)'};throw new Error(`No encontramos una columna que identifique ${missing.map(x=>human[x]).join(' y ')}.`);}if(type==='sales')return parsed.rows.map(r=>({producto:r[found.producto],fecha:r[found.fecha],cantidad:r[found.cantidad],precio:r[found.precio]}));const cost=findColumn(parsed.headers,'costo');return parsed.rows.map(r=>({producto:r[found.producto],stock:r[found.stock],costo:cost?r[cost]:0}));}
async function readTabularFile(file){const ext=file.name.toLowerCase().split('.').pop();if(ext==='csv')return parseCSV(await file.text());if(!['xlsx','xls'].includes(ext))throw new Error('Este formato no es compatible. Puedes cargar archivos Excel (.xlsx, .xls) o CSV.');if(typeof XLSX==='undefined')throw new Error('No pudimos iniciar el lector de Excel. Recarga la página y vuelve a intentarlo.');const workbook=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true});const sheet=workbook.Sheets[workbook.SheetNames[0]];if(!sheet)throw new Error('El archivo no contiene una hoja que podamos leer.');const matrix=XLSX.utils.sheet_to_json(sheet,{header:1,defval:'',raw:false,dateNF:'yyyy-mm-dd'}).filter(row=>row.some(value=>String(value).trim()!==''));if(matrix.length<2)throw new Error('El archivo debe tener encabezados y al menos una fila de información.');const used={};const headers=matrix[0].map((value,index)=>{const base=String(value||`Columna ${index+1}`).trim();used[base]=(used[base]||0)+1;return used[base]>1?`${base} (${used[base]})`:base});return {headers,rows:matrix.slice(1).map(values=>Object.fromEntries(headers.map((header,index)=>[header,values[index]??''])))};}
function numericValue(value){if(typeof value==='number')return value;const cleaned=String(value??'').trim().replace(/\s/g,'').replace(/\.(?=\d{3}(\D|$))/g,'').replace(',','.').replace(/[^\d.-]/g,'');return cleaned!==''&&Number.isFinite(Number(cleaned))?Number(cleaned):NaN;}
function columnProfile(rows,header){const values=rows.slice(0,50).map(r=>r[header]).filter(v=>String(v??'').trim()!=='');const total=values.length||1;const numeric=values.filter(v=>Number.isFinite(numericValue(v))).length/total;const dates=values.filter(v=>/^\d{4}-\d{1,2}-\d{1,2}/.test(String(v))||/^\d{1,2}[\/-]\d{1,2}[\/-]\d{4}$/.test(String(v))).length/total;const text=values.filter(v=>!Number.isFinite(numericValue(v))&&String(v).length>1).length/total;return {numeric,dates,text,sample:values.slice(0,3).join(', ')};}
function semanticScore(header,role,config,profile){const name=normalize(header);let score=0,matched='';for(const term of config.terms){const t=normalize(term);if(name===t&&score<9){score=9;matched=term}else if(name.length>=3&&t.length>=3&&(name.includes(t)||t.includes(name))&&score<6){score=6;matched=term}else{const overlap=t.split(' ').filter(token=>token.length>2&&name.split(' ').includes(token)).length;if(overlap&&score<overlap*2){score=overlap*2;matched=term}}}if(role==='producto'&&/(producto|articulo|descripcion|mercancia)/.test(name))score+=3;if(role==='referencia'&&/(referencia|codigo|sku)/.test(name))score+=3;if(role==='fecha'||role==='ultimoMovimiento')score+=profile.dates*6;if(['cantidad','precio','valorTotal','costo','stock'].includes(role))score+=profile.numeric*3;if(['producto','cliente','canal','referencia'].includes(role))score+=profile.text*2;return {score,reason:matched?`el encabezado se parece a “${matched}” y revisamos una muestra de sus valores`:`la muestra de valores parece compatible con ${config.label.toLowerCase()}`};}
function inferInterpretation(parsed,type){const roles=semanticRoles[type],assignments={},used=new Set();const order=type==='sales'?['fecha','producto','cantidad','precio','valorTotal','costo','cliente','canal']:['producto','stock','costo','ultimoMovimiento','referencia'];for(const role of order){const config=roles[role];const ranked=parsed.headers.filter(h=>!used.has(h)).map(header=>{const profile=columnProfile(parsed.rows,header);return {header,profile,...semanticScore(header,role,config,profile)}}).sort((a,b)=>b.score-a.score);const best=ranked[0];if(!best||best.score<2){assignments[role]=null;continue}const confidence=best.score>=8?'Alta':best.score>=5?'Media':'Baja';if(confidence==='Alta'){for(const [previousRole,previous] of Object.entries(assignments)){if(previous?.header===best.header&&previous.score<best.score)assignments[previousRole]=null}used.add(best.header)}assignments[role]={header:best.header,confidence,score:best.score,reason:best.reason,sample:best.profile.sample}}return {headers:parsed.headers,assignments,rowCount:parsed.rows.length};}
async function readUpload(file,type){if(!file)return;const ext=file.name.toLowerCase().split('.').pop();if(!['xlsx','xls','csv'].includes(ext)||file.size>5*1024*1024){showUploadError('Puedes cargar archivos Excel (.xlsx, .xls) o CSV de máximo 5 MB.');return;}try{const parsed=await readTabularFile(file);showUploadError('');if(app.source!=='custom'||(!app.semanticPending&&app.analysis)){app.dataset=null;app.analysis=null;app.datasetName='';app.uploadNames={sales:'',inventory:''};app.rawUploads={sales:null,inventory:null};app.interpretations={sales:null,inventory:null};app.semanticPending=false;app.source='custom';}app.rawUploads[type]=parsed;app.interpretations[type]=inferInterpretation(parsed,type);app.uploadNames[type]=`${file.name} · ${parsed.rows.length} filas`;const el=$(`#${type==='sales'?'sales':'inventory'}-file-status`);el.textContent=`✓ ${app.uploadNames[type]}`;el.className='file-status success';if(app.rawUploads.sales&&app.rawUploads.inventory){app.semanticPending=true;render();}}catch(err){showUploadError(err.message);}}
function showUploadError(msg){$('#upload-error').textContent=msg;}

function analyze(data){const sales=data.sales||[],inventory=data.inventory||[];const checks=[];let penalties=0;const saleValue=r=>Number.isFinite(numericValue(r.valorTotal))?numericValue(r.valorTotal):numericValue(r.precio);const invalidSales=sales.filter(r=>!r.producto||!/^\d{4}-\d{2}-\d{2}$/.test(r.fecha)||!Number.isFinite(numericValue(r.cantidad))||!Number.isFinite(saleValue(r)));const invalidInv=inventory.filter(r=>!r.producto||!Number.isFinite(numericValue(r.stock)));const negatives=[...sales.filter(r=>numericValue(r.cantidad)<0||saleValue(r)<0),...inventory.filter(r=>numericValue(r.stock)<0)];const dup=new Set(),seen=new Set();sales.forEach(r=>{const k=`${r.fecha}|${r.producto}|${r.cantidad}|${r.precio}|${r.valorTotal}`;if(seen.has(k))dup.add(k);seen.add(k)});const validDates=sales.map(r=>new Date(r.fecha)).filter(d=>!Number.isNaN(d.getTime()));const period=validDates.length>1?Math.round((Math.max(...validDates)-Math.min(...validDates))/86400000):0;const saleProducts=new Set(sales.map(r=>r.producto).filter(Boolean));const invProducts=new Set(inventory.map(r=>r.producto).filter(Boolean));const matches=[...saleProducts].filter(x=>invProducts.has(x)).length;const relation=saleProducts.size?matches/saleProducts.size:0;
const add=(ok,text,cost)=>{checks.push({ok,text});if(!ok)penalties+=cost};add(sales.length>=5&&inventory.length>=2,`Información esencial: ${sales.length} ventas y ${inventory.length} productos de inventario`,30);add(!invalidSales.length&&!invalidInv.length,invalidSales.length+invalidInv.length?`${invalidSales.length+invalidInv.length} fila(s) tienen vacíos, fechas o números inválidos`:'Fechas, productos y números esenciales son válidos',25);add(!negatives.length,negatives.length?`${negatives.length} valor(es) negativo(s) inesperado(s)`:'No encontramos valores negativos inesperados',15);add(!dup.size,dup.size?`${dup.size} registro(s) duplicado(s)`:'No encontramos duplicados exactos',8);add(period>=60,`Periodo disponible: ${period} días`,12);add(relation>=.5,`Coincidencia entre ventas e inventario: ${Math.round(relation*100)}%`,10);
const score=Math.max(0,100-penalties),level=score>=80?'ALTA':score>=55?'MEDIA':'BAJA';const explanation=level==='ALTA'?'La información disponible permite realizar el análisis con buena confianza.':level==='MEDIA'?'Podemos realizar una orientación inicial, aunque encontramos información que sería útil completar.':'La información disponible todavía no permite recomendar qué atender primero con suficiente seguridad.';const metrics=calculateMetrics(sales,inventory,validDates,period);return {quality:{score,level,explanation,checks},metrics,priorities:level==='BAJA'?[]:prioritize(metrics)};}

function calculateMetrics(sales,inventory,dates,period){const valid=sales.filter(r=>r.producto&&Number.isFinite(numericValue(r.cantidad))&&(Number.isFinite(numericValue(r.precio))||Number.isFinite(numericValue(r.valorTotal)))&&numericValue(r.cantidad)>=0);const byProduct={};let revenue=0,units=0;valid.forEach(r=>{const quantity=numericValue(r.cantidad);const value=Number.isFinite(numericValue(r.valorTotal))?numericValue(r.valorTotal):quantity*numericValue(r.precio);revenue+=value;units+=quantity;byProduct[r.producto]=byProduct[r.producto]||{units:0,revenue:0};byProduct[r.producto].units+=quantity;byProduct[r.producto].revenue+=value});const ranked=Object.entries(byProduct).sort((a,b)=>b[1].revenue-a[1].revenue);const topShare=revenue&&ranked[0]?ranked[0][1].revenue/revenue:0;const inv=inventory.filter(r=>r.producto&&Number.isFinite(numericValue(r.stock))).map(r=>({...r,stock:numericValue(r.stock),sold:byProduct[r.producto]?.units||0}));const slow=[...inv].filter(r=>r.stock>=20&&r.sold<=10).sort((a,b)=>(b.stock/(b.sold||.25))-(a.stock/(a.sold||.25)))[0];const stockout=inv.filter(r=>r.stock<=5&&r.sold>0).sort((a,b)=>b.sold-a.sold)[0];return {revenue,units,ranked,topShare,slow,stockout,period,products:inv.length};}
function prioritize(m){const list=[];const concentration={type:'concentration',title:`Reducir la dependencia de ${m.ranked[0]?.[0]||'un solo producto'}`,reason:'Una parte muy alta de las ventas depende de un solo producto.',evidence:`${Math.round(m.topShare*100)}% del valor vendido proviene de ${m.ranked[0]?.[0]||'el producto principal'}.`,indicator:'Porcentaje de ventas que representa el producto principal.'};if(m.topShare>=.8)list.push(concentration);if(m.slow)list.push({type:'slow',title:`Liberar inventario de ${m.slow.producto}`,reason:'Hay muchas unidades almacenadas frente a las unidades vendidas durante el periodo.',evidence:`${m.slow.stock} unidades disponibles y ${m.slow.sold} vendidas en ${m.period} días.`,indicator:`Unidades disponibles de ${m.slow.producto}; deberían disminuir sin generar una nueva compra innecesaria.`});if(m.topShare>=.6&&m.topShare<.8)list.push(concentration);if(m.stockout)list.push({type:'stockout',title:`Evitar quedarte sin ${m.stockout.producto}`,reason:'Tiene ventas registradas y una existencia muy baja.',evidence:`${m.stockout.sold} unidades vendidas y solo ${m.stockout.stock} disponibles.`,indicator:`Días o semanas con producto disponible sin llegar a cero.`});const fallback=[{type:'review',title:'Revisar los productos con pocas ventas',reason:'Algunos productos aportan menos movimiento que los principales.',evidence:m.ranked.length?`${m.ranked[m.ranked.length-1][0]} presenta el menor valor vendido del periodo.`:'La comparación disponible es limitada.',indicator:'Unidades vendidas de los productos con menor movimiento.'},{type:'maintain',title:'Mantener vigilancia sobre los productos principales',reason:'Conviene proteger la disponibilidad de lo que más se vende.',evidence:m.ranked[0]?`${m.ranked[0][0]} lidera las ventas registradas.`:'Se requiere ampliar la información.',indicator:'Existencia disponible de los productos con más ventas.'},{type:'data',title:'Registrar ventas e inventario cada semana',reason:'Una actualización constante permite comparar cambios con mayor confianza.',evidence:`El archivo cubre ${m.period} días.`,indicator:'Número de semanas actualizadas sin interrupción.'}];for(const p of fallback)if(list.length<3&&!list.some(x=>x.type===p.type))list.push(p);return list.slice(0,3);}
function metricCards(){const m=app.analysis.metrics;return `<article class="stat"><span>Ventas registradas</span><strong>${money.format(m.revenue)}</strong></article><article class="stat"><span>Unidades vendidas</span><strong>${m.units}</strong></article><article class="stat"><span>Periodo disponible</span><strong>${m.period} días</strong></article><article class="stat"><span>Producto principal</span><strong>${m.ranked[0]?safe(m.ranked[0][0]):'—'}</strong></article>`;}
function getPlan(){const p=app.analysis?.priorities[0];if(!p)return[];if(p.type==='slow')return[{when:'HOY',action:`Identifica el inventario de ${p.title.replace('Liberar inventario de ','')}`,explain:'Confirma las unidades y si existen pedidos o ventas aún no registradas.'},{when:'ESTA SEMANA',action:'Define una salida responsable',explain:'Evalúa promoción, combo o pausa temporal de nuevas compras.'},{when:'EN 14 DÍAS',action:'Compara el inventario nuevamente',explain:'Revisa si las existencias bajaron y registra qué funcionó.'}];if(p.type==='concentration')return[{when:'HOY',action:'Confirma cuánto depende la venta del producto principal',explain:'Revisa si el patrón se mantiene en semanas anteriores.'},{when:'ESTA SEMANA',action:'Elige dos productos complementarios',explain:'Prueba una exhibición o comunicación conjunta sin cambiar precios a ciegas.'},{when:'EN 14 DÍAS',action:'Mide nuevamente la concentración',explain:'Compara el porcentaje aportado por el producto principal.'}];if(p.type==='stockout')return[{when:'HOY',action:'Confirma existencia y pedidos pendientes',explain:'Verifica físicamente el producto antes de comprar.'},{when:'ESTA SEMANA',action:'Ajusta el siguiente pedido',explain:'Considera ventas recientes y tiempo de entrega del proveedor.'},{when:'EN 14 DÍAS',action:'Revisa si evitaste el agotado',explain:'Registra los días con disponibilidad y posibles ventas perdidas.'}];return[{when:'HOY',action:'Revisa la información señalada',explain:'Confirma que el registro representa la operación real.'},{when:'ESTA SEMANA',action:'Prueba una mejora pequeña',explain:'Cambia una sola cosa para poder observar su efecto.'},{when:'EN 14 DÍAS',action:'Compara el indicador',explain:p.indicator}];}
function updateTask(e){app.tasks[Number(e.target.dataset.task)]=e.target.value;if(app.step===8){const done=app.tasks.filter(x=>x==='Completada').length;$('#task-count').textContent=`${done}/3`;}}
function updateOwner(e){app.owners[Number(e.target.dataset.task)]=e.target.value;}
function saveFeedback(e){e.preventDefault();app.feedback=Object.fromEntries(new FormData(e.currentTarget));app.completed.feedback=true;go(10);}
function showTestSummary(){const steps=[['Demostración iniciada',app.completed.start],['Contexto completado',app.completed.form],['Datos procesados',app.completed.data],['Calidad evaluada',app.completed.quality],['Prioridad generada',app.completed.priority],['Plan de acción generado',app.completed.plan],['Avance registrado',app.completed.feedback]];const count=steps.filter(x=>x[1]).length;const elapsed=app.start?Math.max(1,Math.round((Date.now()-app.start)/60000)):0;$('#test-dialog-content').innerHTML=`<p class="eyebrow">Evidencia funcional</p><h2>Resultados de la prueba</h2><h3>${count}/7 hitos completados exitosamente</h3><div class="step-results">${steps.map(x=>`<div class="step-row"><span>${x[0]}</span><b>${x[1]?'Completado':'Pendiente'}</b></div>`).join('')}</div><div class="stats-grid"><article class="stat"><span>Tiempo aproximado</span><strong>${elapsed} min</strong></article><article class="stat"><span>Fuente</span><strong>${safe(app.datasetName||'Sin elegir')}</strong></article><article class="stat"><span>Calidad</span><strong>${app.analysis?.quality.level||'—'}</strong></article><article class="stat"><span>Prioridad</span><strong>${safe(app.analysis?.priorities[0]?.title||'No generada')}</strong></article></div><p class="screen-intro">Este resumen no almacena información personal real.</p>`;$('#test-dialog').showModal();}

function downloadExecutiveSummary(){
  if(!app.analysis||app.analysis.quality.level==='BAJA')return;
  const p=app.analysis.priorities[0],plan=getPlan();
  const context=Object.entries(app.context).filter(([,value])=>value).map(([key,value])=>`<li><strong>${safe(key.replace(/([A-Z])/g,' $1'))}:</strong> ${safe(value)}</li>`).join('')||'<li>Contexto demostrativo no especificado.</li>';
  const findings=app.analysis.priorities.map((item,i)=>`<li><strong>${i+1}. ${safe(item.title)}</strong><br>${safe(item.evidence)}</li>`).join('');
  const actions=plan.map((item,i)=>`<tr><td>${safe(item.action)}</td><td>${safe(app.owners[i]||'Por definir')}</td><td>${safe(item.when)}</td><td>${safe(p.indicator)}</td></tr>`).join('');
  const reportHtml=`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Resumen ejecutivo · San José</title><style>body{font-family:Arial,sans-serif;color:#1f2937;max-width:900px;margin:40px auto;padding:0 20px;line-height:1.5}h1,h2{font-family:Georgia,serif;color:#011235}header{border-bottom:4px solid #D8A63A;padding-bottom:18px}.tag{color:#A36F08;font-weight:700;text-transform:uppercase;letter-spacing:.08em}section{margin:28px 0}table{width:100%;border-collapse:collapse;font-size:13px}th,td{border:1px solid #E5E7EB;padding:10px;text-align:left;vertical-align:top}.priority{background:#f8f6f0;border-left:5px solid #D8A63A;padding:20px}button{background:#011235;color:white;border:0;padding:12px 18px;border-radius:4px}@media print{button{display:none}body{margin:15mm;padding:0}}</style></head><body><header><p class="tag">San José · Transformación Empresarial</p><h1>Resumen ejecutivo</h1><p>Orientación inicial basada en ventas e inventario.</p><small>Fecha: ${new Intl.DateTimeFormat('es-CO',{dateStyle:'long'}).format(new Date())}</small></header><section><h2>Contexto general</h2><ul>${context}</ul></section><section><h2>Calidad de los datos</h2><p><strong>${app.analysis.quality.level} · ${app.analysis.quality.score}/100</strong></p><p>${safe(app.analysis.quality.explanation)}</p></section><section><h2>Principales hallazgos</h2><ol>${findings}</ol></section><section class="priority"><p class="tag">Prioridad número 1</p><h2>${safe(p.title)}</h2><p>${safe(p.evidence)}</p><p><strong>Qué hacer primero:</strong> ${safe(priorityGuidance(p).action)}</p></section><section><h2>Plan de acción</h2><table><thead><tr><th>Acción</th><th>Responsable</th><th>Plazo</th><th>Indicador</th></tr></thead><tbody>${actions}</tbody></table></section><section><h2>Limitaciones</h2><ul><li>El análisis inicial se concentra en ventas e inventario.</li><li>Las conclusiones dependen de la calidad y cobertura de los archivos.</li><li>No se utiliza un modelo remoto de inteligencia artificial.</li><li>La decisión final corresponde al empresario.</li></ul></section><p><button onclick="window.print()">Imprimir o guardar como PDF</button></p></body></html>`;
  const blob=new Blob([reportHtml],{type:'text/html;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');
  link.href=url;link.download='resumen-ejecutivo-san-jose.html';document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
